### ISSUE TITLE
S3-extend with ConfigurableFirmata

### ISSUE THREAD

**Issue by ruebox** [MrYsLab/s3-extend#23]
@MrYsLab 
Thanks a lot for the great framework for connecting Scratch3 with Arduino and others. I have Microduino running at home and try to integrate this also to your s3-extend framework.
Due to your elaborate documentation, I was able to add a scratch extension ... thanks.

However, I would need to extend the FirmataExpress with other devices. I am an experience C++ programmer and like the code structure and flexibility of ConfigureableFirmata to easily add features ... 

Could you give me a hint how to run s3-extend with ConfigurableFirmata as 
```
python3 s3a.py 
backplane started
Websocket Gateway started
Arduino Gateway started.
Please wait 0 seconds for Arduino to initialize...
Arduino is initialized.
To exit this program, press Control-c
Arduino Gateway exited. Is your Arduino plugged in?
```
directly fails without pressing Control-C.

Thanks for this.
Best,
Ruebox

**Comment by MrYsLab** [comment]
Hi Ruebox,
    You will need to implement addtional SYSEX commands for the [RU_THERE/I_AM_HERE  challenge and reply](https://github.com/MrYsLab/FirmataExpress/blob/60f1c249004293e711ace25ddda95c2266d4212a/examples/FirmataExpress/FirmataExpress.ino#L588). You may already be aware of this, but let me mention the following in case you are not. The extension not only uses FirmataExpress, but also [pymata-express](https://github.com/MrYsLab/pymata-express). The Ardino link speed is set to 115200.

To get an understanding of what pymata-express needs to proceed  is essentially:

1. Firmata must be able to return its[ firmware version when queried.](https://github.com/MrYsLab/pymata-express/blob/4905c8ccaf88efa3802a2f1f8b330c45c9a38e07/pymata_express/pymata_express.py#L277)
2. Firmata must be able to r[eturn its analog map](https://github.com/MrYsLab/pymata-express/blob/4905c8ccaf88efa3802a2f1f8b330c45c9a38e07/pymata_express/pymata_express.py#L296).
3. And Firmata must be able to participate in the pymate-express's auto-discovery protocol by returning an [Arduino instance ID.](https://mryslab.github.io/pymata-express/firmata_express/#setting-the-firmataexpress-instance-id)

Just to let you know, I have developed a much more flexible and simpler alternative to Firmata called [Telemetrix](https://mryslab.github.io/telemetrix/). I will be porting the extensions over to Telemetrix in the future, and at that time will no longer support the Firmata extensions.

I am going to close this issue, but if you have any additional questions, you may post them here and I will see them.
