### ISSUE TITLE
No errors but "blink sketch" doesn't work on esp8266

### ISSUE THREAD

**Issue by Anton-V-K** [MrYsLab/s3-extend#33]
I've followed your great tutorial trying to imitate standard Blink sketch in Scratch, but it just doesn't work - the LED doesn't blink. All servers are running fine, even the firmware indicates that the client connects when I start the scratch program.
OS: Windows 10 Home 64-bit (Version 10.0.18362)
MCU: LoLin esp8266 (NodeMCU V3) as "NodeMCU 1.0 (ESP12-E Module)" in Arduino's Boards Manager.
Arduino 1.8.15

The sketch I've used to test the LED:
```
#define LED_PIN D1 // D1=GPIO5 (for external LED) or LED_BUILTIN (for built-in LED)

void setup() {
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_PIN, HIGH);        // turn the LED on (HIGH is the voltage level)
  delay(1000);                        // wait for a second
  digitalWrite(LED_PIN, LOW);         // turn the LED off by making the voltage LOW
  delay(1000);                        // wait for a second
}
```

The Scratch blocks:
![ESP8266_LED](https://user-images.githubusercontent.com/20116984/137349236-b5e737b5-108c-4f81-8542-625b9abf9aa4.png)
I assume the pin numbers are referencing to GPIO numbers. Is this so?
Here is the project for your reference - [ESP8266_LED.sb3.zip](https://github.com/MrYsLab/s3-extend/files/7347432/ESP8266_LED.sb3.zip)

`s3e` normally doesn't work (even after reboot):
```
C:\Users\Anton>s3e
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python310-32\Scripts\s3e.exe\__main__.py", line 7, in <module>
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\s3_extend\s3e.py", line 202, in s3ex
    S3E()
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\s3_extend\s3e.py", line 49, in __init__
    self.proc_bp = self.start_backplane()
  File "C:\Program Files (x86)\Python310-32\lib\site-packages\s3_extend\s3e.py", line 151, in start_backplane
    if 'backplane' in proc.info['name']:
TypeError: argument of type 'NoneType' is not iterable
```
So I proceed with running servers individually:
```
C:\Users\Anton>backplane

******************************************
Backplane IP address: 192.168.1.48
Subscriber Port = 43125
Publisher  Port = 43124
Loop Time = 0.001 seconds
******************************************
```
```
C:\Users\Anton>espgw
TelemetrixAIO Version: 1.7
Copyright (c) 2018-2020 Alan Yorinks All rights reserved.


************************************************************
ESP8266Gateway using Back Plane IP address: 192.168.1.48
Subscriber Port = 43125
Publisher  Port = 43124
************************************************************
set_pin_mode: callback ignored for pin state: 1
Successfully connected to: 192.168.1.64:31335
Telemetrix4Arduino Version Number: 3.0.0
```
The last 3 (three) lines above are shown when I start the scratch program, so it apparently does connect to ESP8266.

```
C:\Users\Anton>wsgw -i 9002

************************************************************
WebSocket Gateway using Back Plane IP address: 192.168.1.48
Subscriber Port = 43125
Publisher  Port = 43124
************************************************************
WebSocket using: 192.168.1.48:9002
```

The firmware also runs fine:
```
Connected to WiFi. IP Address: 192.168.1.64  IP Port: 31335
Client Connected to address: 192.168.1.48
```

PC restart doesn't help.
I've also tried running Scratch online and locally.

Where else to look? What could be the problem?

**Comment by MrYsLab** [comment]
I forgot to mention that you also need to edit the Arduino sketch for your network SSID and Password:
At line 30 of the sketch:

```
// Modify the next two lines to match your network values
const char *ssid = "YOUR_SSID";
const char *password = "YOUR_PASSWORD";
```

**Comment by MrYsLab** [comment]
The pin is set to output as shown in the monitor line:
```
to_esp8266_gateway {'command': 'set_mode_digital_output', 'pin': 5}
```
I connected a discrete LED using the following instructions from [this article:](https://www.instructables.com/NodeMCU-Basic-Project-Blink-a-LED/)
```
Connect one end of the resistor to the digital pin correspondent to the LED_BUILTIN constant.

Connect the long leg of the LED (the positive leg, called the anode) to the other end of the resistor.

Connect the short leg of the LED (the negative leg, called the cathode) to the GND. 
```
The Scratch script I am using is shown below. I manually click on the IP address block once and then use the green flag to run the script.

It blinks the light as expected.

I don't know how your RGB board is wired, but using a single discrete LED works. I am not doing anything special in terms of wiring. If you can, could you please try using a discrete LED and resistor to test?
![Screenshot from 2021-10-15 17-21-00](https://user-images.githubusercontent.com/5189838/137556052-c92e989d-acf6-42a8-bfaa-5e3ef7f9cd5d.png)

**Comment by Anton-V-K** [comment]
@MrYsLab , your hack does work! I was able to blink LED after that :)
Moreover reading from this pin before the loop also does the trick, and no delay is needed:
![ESP8266_LED-debug](https://user-images.githubusercontent.com/20116984/137596550-f2aa07d7-e592-40c3-97d9-622371d2c7da.png)
Here is the monitor log:
```
C:\Users\Anton>monitor

************************************************************
Monitor using Back Plane IP address: 192.168.1.48
Subscriber Port = 43125
Publisher  Port = 43124
Loop Time = 0.1 seconds
************************************************************
to_esp8266_gateway {'command': 'ip_address', 'address': '192.168.1.64'}
to_esp8266_gateway {'command': 'set_mode_digital_input', 'pin': 5}
to_esp8266_gateway {'command': 'set_mode_digital_output', 'pin': 5}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
```
Here is the log from esp8266:
```
Connected to WiFi. IP Address: 192.168.1.64  IP Port: 31335
Client Connected to address: 192.168.1.48
get_next_command: packet_length = 1, command = 5
get_next_command: packet_length = 1, command = 17
get_next_command: packet_length = 1, command = 18
get_next_command: packet_length = 3, command = 1
set_pin_mode: pin = 5, mode = 1
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
get_next_command: packet_length = 3, command = 2
```
Note that esp8266 got only one SET_PIN_MODE command.

During further experiments I noticed that pin mode command could be skipped completely (it isn't shown in monitor at all!):
```
C:\Users\Anton>monitor

************************************************************
Monitor using Back Plane IP address: 192.168.1.48
Subscriber Port = 43125
Publisher  Port = 43124
Loop Time = 0.1 seconds
************************************************************
to_esp8266_gateway {'command': 'ip_address', 'address': '192.168.1.64'}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 0}
to_esp8266_gateway {'command': 'digital_write', 'pin': 5, 'value': 1}
```
Probably PC reboot is needed...
It seems there is an issue in your scripts which makes their behavior unpredictable in some environments or/and under some conditions.

**Comment by MrYsLab** [comment]
Would you be willing to try one other test?
I have test programs for both [asyncio ](https://github.com/MrYsLab/telemetrix-aio/blob/master/examples/wifi/blink_wifi.py)(which is used by s3-extend) and [non-asyncio](https://github.com/MrYsLab/telemetrix/blob/master/examples/wifi/blink_wifi.py) that blink an LED.

For both, you would need to edit the IP address to match that of your ESP8266 and change the pin number for the LED.

I would be curious to know if either or both of these programs successfully blink the LED.

**Comment by MrYsLab** [comment]
Thanks for providing that information. The problem is consistent in that the first message coming from your browsers somehow does not get executed. In Scratch, the "Write Digital Block" sets the pin mode for a pin the first time the block is executed. After that, only the command to set the pin's state is sent. The Monitor's output reflects this behavior. 

I see you are using 32-bit browsers. I assume then that your version of Windows 10 is 32 bit as well. If that is true, I suspect that somehow, the 32-bit version of either the browsers, Windows 10, or a combination of the two is causing this behavior.

I do not have access to a 32-bit system, so I cannot test this theory or determine its cause.

If you have access to a 64-bit system and run the program, my guess is that the program will run as expected. As I mentioned earlier, several hundred students use the ESP-8266 with Scratch, but I know that they are using 64-bit software versions.

At this point, I am not sure how to proceed. If using a "dummy" read block as the first instruction after executing the IP address block is not objectionable, this may be the simplest solution.

**Comment by Anton-V-K** [comment]
@MrYsLab , thanks for looking into this.
The emulator script works fine without changing the delays - the LED is blinking very fast.
If I remove all delays at the setup phase (before the loop), the issue comes back - `set_pin_mode` isn't called, and the LED isn't blinking.

**Comment by MrYsLab** [comment]
A quick update. I found the cause of the problem when running the WebSocket test script, and I think it is probably the cause of what you see in your environment. The ESP8266 gateway is a special case compared to all the other gateways. The gateway has a continuous running task that receives incoming messages from Scratch. When the gateway receives the message from the Scratch IP address block, it initiates the IP connection to the ESP8266. While this connection is in progress, the set_pin_mode_digtial_output is received, and it tries to send out the command to the ESP8266 even though the connection is not complete.

I need to decide how to fix this race condition. There are a couple of options. The first is using an asyncio synchronization primitive between the two tasks. 

The other is to run the message receiving task to receive a single IP address message and then exit.  This message initiates the IP connection, and when the connection completes, the message receiving task is started again to run continuously. I believe the system will buffer any messages sent from Scratch when the receive task is down waiting for the IP connection. I need to verify that this is true, and if it is, I will probably be going with this second.

I will be taking the next few days to implement and test things out. When it is complete, I will let you know.
