### ISSUE TITLE
Cannot start s3e on Windows 10 x64 with Python 3.9.7 x86

### ISSUE THREAD

**Issue by Anton-V-K** [MrYsLab/s3-extend#36]
I'm unable to start `s3e` on Windows 10 64-bit with Python 3.9.7 32-bit:
```
C:\Users\Anton>s3e
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files (x86)\Python39-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files (x86)\Python39-32\Scripts\s3e.exe\__main__.py", line 7, in <module>
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\s3_extend\s3e.py", line 202, in s3ex
    S3E()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\s3_extend\s3e.py", line 49, in __init__
    self.proc_bp = self.start_backplane()
  File "C:\Program Files (x86)\Python39-32\lib\site-packages\s3_extend\s3e.py", line 151, in start_backplane
    if 'backplane' in proc.info['name']:
TypeError: argument of type 'NoneType' is not iterable
```
Other servers (namely `backplane`, `espgw`, `wsgw` and `monitor`) run fine, when started individually.

Here is the test script (rewritten fragment of `start_backplane` from `s3e.py`):
```
import psutil

# check to see if the backplane is already running
try:
    for proc in psutil.process_iter(attrs=['pid', 'name']):
        print(proc.info['pid'], proc.info['name']) # list all found processes
        if 'backplane' in proc.info['name']:
            self.skip_backplane = True
            print(proc) # found!
except (psutil.NoSuchProcess, psutil.AccessDenied, psutil.ZombieProcess):
    pass
```

Output:
```
...>python test_s3e.py
0 System Idle Process
4 System
120 Registry
268 None
Traceback (most recent call last):
  File "D:\Anton\Devel\Arduino\Telemetrix4Esp8266\test_s3e.py", line 9, in <module>
    if 'backplane' in proc.info['name']:
TypeError: argument of type 'NoneType' is not iterable
```
Screenshot from Task Manager:
![2021 10 25-Task_Manager-very_long_process_name](https://user-images.githubusercontent.com/20116984/138694562-9c31095e-09ee-4bff-83f4-089dab6b2023.png)

It looks like another bug in `psutil` - see https://github.com/giampaolo/psutil/issues/1980 where the module can't properly handle long names (due to "bitness mismatch").

I'm not sure whether a process can run without a name, but it may be worth checking the returned string (is it empty?) before trying to search for `backplane` in it (yeah, it's a kind of hack/workaround).

Another **possible workaround** it to use same 'bitness' both for Python, and for Windows.

**Comment by Anton-V-K** [comment]
[psutil 5.9.0](https://github.com/giampaolo/psutil/releases/tag/release-5.9.0) was released, so this issue shouldn't happen any longer

**Comment by MrYsLab** [comment]
I just installed s3-extend using Python 3.9.7 on Windows 10 without any issues. If you are still seeing the same errors you posted above, and still have **windowsinternal.composableshell.experiences.textinput.inputapp.exe,**
running, then this is something peculiar to your Windows environment. I still have no idea why that application is running on your system and not mine.
