### ISSUE TITLE
Problem with starting s3r on raspberry pi

### ISSUE THREAD

**Issue by almo2022** [MrYsLab/s3-extend#42]
Hello again. My raspi is giving me an error when starting s3r: ![20231224_115845.jpg](https://github.com/MrYsLab/s3-extend/assets/105065433/021efb05-89e5-47a3-86a9-c9b6e71b4971)
This error I had several times bevore. Can someone help me?

**Comment by MrYsLab** [comment]
The s3r application depends on the [pigpio library](https://abyz.me.uk/rpi/pigpio/) that controls the GPIO pins of the Raspberry Pi. You don't need to understand pigpio; I am only providing the link if you are interested.

The pigpio library is incompatible with pipx. However using a venv virtual environment will solve the problem. I will explain what you need to do to set one up and how to use it. It complicates things more than pipx, but it is the only choice.

First, remove the pipx versions of python_banyan and s3-extend:
```
pipx uninstall python_banyan

pipx uninstall s3-extend
```

Next, install venv into the system:
```
sudo apt install python3-venv
```

Create the virtual environment. The example I am using will create a virtual environment in a directory called s3ex. This directory will reside within the home directory. You may use any name you wish.

```
python3 -m venv s3ex
```
![Screenshot from 2023-12-24 12-28-12](https://github.com/MrYsLab/s3-extend/assets/5189838/312bf186-b943-422a-a196-9375783e9d18)

The virtual environment needs to be activated. Here is the command to do this:
```
source ~/s3ex/bin/activate

```

Now, the prompt in the command changes to indicate that the virtual environment is activated.
![Screenshot from 2023-12-24 12-33-54](https://github.com/MrYsLab/s3-extend/assets/5189838/717de1d5-4fe8-4ca3-a16f-2e73da18a862)

Install s3-extend and pigpio

```
pip install s3-extend

pip install  pigpio

```
Run s3r

![Screenshot from 2023-12-24 12-39-23](https://github.com/MrYsLab/s3-extend/assets/5189838/cdf8eb31-c5f0-4dd1-a2a6-3572ebf787c2)

To deactivate the virtual environment, close the terminal window. You must reactivate anytime you close the terminal window, log out, or reboot.

Please let me know if this works for you.

Have a happy holiday!

**Comment by MrYsLab** [comment]
I am closing this issue. If you have any problems or questions, you may post them here, and I will see them. Thanks.

**Comment by almo2022** [comment]
No, everything works as it should. Thanks. ❤️
