### ISSUE TITLE
Websocket is closing unexpectedly 

### ISSUE THREAD

**Issue by codezuma** [MrYsLab/s3-extend#50]
After starting the s3a library I get this error.
![image](https://github.com/user-attachments/assets/ddc87f6d-57ef-46d1-af89-93042acb23d2)

I tried running backplane,ardgw, and wsgw. 
backplane and ardgw seems to be running fine but wsgw closes before even starting 
![image](https://github.com/user-attachments/assets/df691663-1e5a-465d-afb6-8443b32f4415)

**Comment by noud-github** [comment]
Hi I had te same issue downgrading websockets to 13.1 fixed it on both windows and linux,

pip install --force-reinstall -v "websockets==13.1"

followed that as documnetation of websockets 14.1 show that it broke a lot of backwards compatibiltatie's

**Comment by noud-github** [comment]
not sure, but I think it now says your arduino can be reached,
so I think a reset of the arduino might fix that or a previus s3-extend program is still running and keeping it ocupited,
a reboot of you PC might fix that if you cannot find the couse ;-)

**Comment by MrYsLab** [comment]
I uploaded version 1.31 to pypi, which should fix the issue. 

You can upgrade with the following pip command:

```
pip install --upgrade s3-extend
```

**Comment by MrYsLab** [comment]
I am closing the issue.

**Comment by MrYsLab** [comment]
Sorry folks. It looks like the problem still exists. I am working on it.

**Comment by MrYsLab** [comment]
I apologize to all since I did not fix the problem. I was testing in an environment that masked it.
Version 1.33 fixes the problem. Part of the solution was to force python_banyan, which this library uses, to use version 13.1 of websockets.

**Comment by MrYsLab** [comment]
You may need to remove python_banyan before installing the new version s3-extend:
```
pip uninstall python_banyan
```
